server:
  port: 8080
  tomcat:
      uri-encoding: utf-8
      #指定文件上传服务器临时目录，避免服务器自动清理目录的问题 “.”表示项目启动目录
      basedir: ${hope.work-dir}
  # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true

#文件上传
web:
  upload-path: ${hope.work-dir}/images/

spring:
  application:
    name: hope-admin
  profiles:
    active: dev
  #数据库配置
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hope?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      filters: stat,wall,slf4j
  # Redis
  redis:
      database: 12
      host: localhost
      port: 6379
      #密码默认为空，注释即可，要添加密码，去掉注释添加就行
      #password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #模板引擎配置
  thymeleaf:
    # 配置thymeleaf修改页面不重启生效
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
  #配置自定义静态文件的位置
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

#mybatis
mybatis:
    type-aliases-package: com.hope.model.bean
    mapper-locations: classpath:mapper/*.xml

#日志
logging:
    file:
      path: ${hope.work-dir}/logs/${spring.application.name}/${spring.application.name}.log
    level:
      com.hope: DEBUG
      org.springframework: WARN
      com.baomidou.mybatisplus.samples.quickstart: debug

#阿里云短信接入配置
sms:
  accessKeyId:
  accessKeySecret:
  templateCode:
  signName:

#第三方登录配置 去对应的第三方创建应用 本地测试开内网穿透
justauth:
  enabled: true
  type:
    GITEE:
      client-id:
      client-secret:
      redirect-uri: http://aodeng.cn1.utools.club/oauth/gitee/callback
  cache:
    type: default

#又拍云配置：空间名称，操作员名称，操作员密码，图片上传路径，其他文件上传路径，域名，协议
upyun:
  BUCKET_NAME: ddxxm-aodeng
  OPERATOR_NAME: aodeng
  OPERATOR_PWD: hdsBLUHVy9ERg3LuoEjG0TCs0sa06ReV
  YP_IMAGE_PATH: /image/
  YP_FILE_PATH: /file/
  YP_DOMAN: ddxxm-aodeng.test.upcdn.net
  YP_PROTOCOL: http://

hope:
    work-dir: ${user.home}/.hope/${spring.profiles.active}/
