server:
  port: 8080
  tomcat:
      uri-encoding: utf-8
      #指定文件上传服务器临时目录，避免服务器自动清理目录的问题 “.”表示项目启动目录
      basedir: ${hope.work-dir}
  # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true

#文件上传
web:
  upload-path: ${hope.work-dir}/images/

spring:
  application:
    name: hope-admin
  profiles:
    active: dev
  #数据库配置
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${hope.server-host-ip}:3306/yt-devicedb-test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      # 连接池
      hikari:
        #连接池名
        pool-name: DateHikariCP
        #最小空闲连接数
        minimum-idle: 5
        # 空闲连接存活最大时间，默认600000（10分钟）
        idle-timeout: 180000
        # 连接池最大连接数，默认是10
        maximum-pool-size: 10
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        max-lifetime: 1800000
        # 数据库连接超时时间,默认30秒，即30000
        connection-timeout: 30000
        connection-test-query: SELECT 1
  # Redis
  redis:
      database: 12
      host: ${hope.server-host-ip}
      port: 6379
      #密码默认为空，注释即可，要添加密码，去掉注释添加就行
      #password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #模板引擎配置
  thymeleaf:
    # 配置thymeleaf修改页面不重启生效
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
  #配置自定义静态文件的位置
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  #最大支持文件大小,请求大小设置
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      resolve-lazily: true
  #发送电子邮件服务配置 账号，密码修改
  mail:
    host: smtp.qq.com
    username: 123456789@qq.com
    password: 987654321
    default-encoding: UTF-8
    #邮件 SSL Config 阿里云服务器发送需要配置
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory
#以谁来发送邮件
mail.fromMail.addr: 123456789@qq.com

#mybatis
mybatis:
    type-aliases-package: com.hope.model.bean
    mapper-locations: classpath:mapper/*.xml
#mybatis plus
mybatis-plus:
  configuration:
    #是否启用驼峰命名
    map-underscore-to-camel-case: true

#日志
logging:
    file:
      path: ${hope.work-dir}/logs/${spring.application.name}/${spring.application.name}.log
    level:
      com.hope: DEBUG
      org.springframework: WARN
      com.baomidou.mybatisplus.samples.quickstart: debug

#阿里云短信接入配置
sms:
  accessKeyId:
  accessKeySecret:
  templateCode:
  signName:

#第三方登录配置 去对应的第三方创建应用 本地测试开内网穿透
justauth:
  enabled: true
  type:
    GITEE:
      client-id:
      client-secret:
      redirect-uri: http://aodeng.cn1.utools.club/oauth/gitee/callback
  cache:
    type: default

#又拍云配置：空间名称，操作员名称，操作员密码，图片上传路径，其他文件上传路径，域名，协议
upyun:
  BUCKET_NAME: ddxxm-aodeng
  OPERATOR_NAME: aodeng
  OPERATOR_PWD:
  YP_IMAGE_PATH: /image/
  YP_FILE_PATH: /file/
  YP_DOMAN: ddxxm-aodeng.test.upcdn.net
  YP_PROTOCOL: http://

hope:
    work-dir: ${user.home}/.hope/${spring.profiles.active}/
    server-host-ip: 127.0.0.1

