server:
  port: 8886
  tomcat:
      uri-encoding: utf-8
  # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true

spring:
  application:
    name: hope-admin
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/DeviceDB?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      filters: stat,wall,slf4j
  # Redis
  redis:
      database: 12
      host: localhost
      port: 6379
      #密码默认为空，注释即可，要添加密码，去掉注释添加就行
      password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    # 配置thymeleaf修改页面不重启生效
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5

mybatis:
    type-aliases-package: com.hope.model.bean
    mapper-locations: classpath:mapper/*.xml

logging:
    file: ./logs/log.log
    level:
      com.hope: DEBUG
      org.springframework: WARN
      com.baomidou.mybatisplus.samples.quickstart: debug

sms:
  accessKeyId:
  accessKeySecret:
  templateCode:
  signName: